---
firewall:
  ports:
    - 8443
    # - 9000

step_ca_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  62393831323963323561303663313462323035353264633566303439636638316332616465663861
  3964333861383065353464313737613363653863623636630a353431656337656362323230623830
  32376435353939626561316137323733396661323134636661616437653362353766643137616334
  6261346464356335360a373361303634633361363335616565366233346634386661353239356133
  66363964626131633435643837373635393861373163363931303839343738366461646137356638
  3039636439623163313635613032333635316432646237346365
