---
unbound_local_zones:
  - name: "server.acme."
    type: static

unbound_local_data:
  - "dns.server.acme. IN A 10.0.50.10"
  - "vpn.server.acme. IN A 10.0.50.11"
  - "cloud.server.acme. IN A 10.0.50.12"
