---
- name: Apply sysctl
  ansible.builtin.command:
    cmd: sysctl -p /etc/sysctl.d/99-openvpn.conf
  changed_when: false

- name: Restart openvpn
  ansible.builtin.systemd:
    name: openvpn-server@{{ openvpn_server_name }}
    state: restarted

- name: Restart openvpn-auth-oauth2
  ansible.builtin.systemd:
    name: openvpn-auth-oauth2
    state: restarted
