$ANSIBLE_VAULT;1.1;AES256
38656437303863646364616463656461373734383165646130363136643864616235333932613139
3039386439303130316433653063656166323235386366310a383061323365623739353330346361
36333735326361333830386163663430613564616364303035376661343834313335343631363933
3661633064366165640a316238366439333130643234316434643435656336356632366537316531
33306133333163373564323231373563323765623430393631393565653133303338363766373361
66333633353632343735316536353832616532393835383365303638303334316461363362363934
30643863653061663231323434343761613230623239323039386237653430376230366465623430
32306466393631386538306230646338356437303063316339323336646661343164373039343465
31386530653438353031376234616537313264623031646363333633326263646464373537373361
38376533643465363963323833346465356663633730386466333961613037356135316534336263
30326462346133323733643136633435333536303661356663306332313363613265356333343666
33303239303036306631613166323437313139616463363165373363373262373836336565396234
33363432343163336537356339323861383663383165336263636465353337643733333538386564
33306564393135636633373835393730356430636335356539363864383063386639393034636631
63306638393237366164633936343330323431653536356532363165346239343635653434363966
31666638643662313438
