---
vault_openvpn_oauth2_client_id: "openvpn"
vault_openvpn_oauth2_client_secret: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  61613666633636353331323663313662383931323638396262376439393262363964393436633533
  6565623037396133613061306363623763646164643930360a623161363235633334656535366136
  62353331386662663337326632393266616561373330313263646666326562663263313665386631
  3131383965346234320a326538656433613264376636386266346536323764373163666461346637
  66306264323865303939386431383038666465326632303064393562666638343236623363396436
  6133633234613261363732336538386432646136313330363632
vault_openvpn_mgmt_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  37303966626636356134623562373339343039346461306265353339663138663764353632376463
  3066363866373765306334366638386336343734316666660a326463346561373035303735356235
  65376465363635666132653132393363643262643735373839373437663537636465656435363534
  3730646234336163380a653166336365633932356562393736376361666337626264363933303566
  31333637393730613865366264323066633930383166363731306532336135366136
vault_openvpn_oauth2_http_secret: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  62666561623861326532393735643337353061333165393839303030623731663739343031383533
  3361633635646131613230383762653865386335633738340a333637313161383963343039666637
  65376637303735643861323334613239376636666337643531623263356437326334643631653361
  6535636366636465620a366631623166623163386535336237643163623665366336326436313136
  63333932616234623132623063623639313466656335663135323137653534623865613431303166
  3631646538333433383430656463353563383136623433366635
