---
freeradius_clients:
  - name: stockholm-router
    ipaddr: 10.0.10.1
    secret: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      66653534633861343163633330353564656133373938613934353236623066333338336561643661
      3866353363323166663764623561646365363563383139390a343363363333363335363830373933
      38663563336362653538666230393665643630306331326437613163363431663562343737333861
      3938353231643233640a313837366438623731363738623866613931373165383165313933363038
      34326365653939333536613037653435303364326239343134346633353835656131636132636336
      64656364633732623531323632663939623037616332393661316362313732366333386639363565
      633162343032373635323463356330346237
  - name: london-router
    ipaddr: 10.0.20.1
    secret: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      33386431623866313430616262633239653763653236313836656361646264306535366662356339
      3437353337653336346535393163623334346534363837360a373663386333303836616162636636
      35313666663331616231653639303266336431356266346264343666663861663839363439313732
      3835633934656233350a626635646138323935306135376165633935386132346364336633393163
      34313635326437323462356631643566643961656638653339373433303730646437623633376562
      63613538626165356461663931663537336231633663373934643537643139316232393464623539
      616132353531323537306239386365623034
